### PR TITLE
Updates to form examples, inline link and form control components

### PR DESCRIPTION
**Pull request by rezrah**
## Summary

Updates to form recipes, form control and inline link components.

🔗 [See form example changes in Storybook](https://primer-883531b99b-26139705.drafts.github.io/storybook/?path=/story/recipes-feature-previews-level-1--level-one-side-by-side)
🔗 [See form control changes in Storybook](https://primer-883531b99b-26139705.drafts.github.io/storybook/?path=/story/components-forms-formcontrol--text-input-playground)
🔗 [See inline link changes in Storybook](https://primer-883531b99b-26139705.drafts.github.io/storybook/?path=/story/components-inlinelink--size-inheritence)

## List of notable changes:

- **updated** InlineLink underline to now work across multiple lines.
- **updated** InlineLink dark mode colors to match recent changes to Link
- **updated** FormControl labels from 14px to 16px to match labels in Figma
- **updated** Side by side form example recipes to match latest designs

## What should reviewers focus on?

- Review the side by side story example, and toggle between `default` and `extended` form type controls to see different versions.
- Check inline link color values are correct and appear correctly across multiple lines

## Steps to test:

🔗 [See form example changes in Storybook](https://primer-883531b99b-26139705.drafts.github.io/storybook/?path=/story/recipes-feature-previews-level-1--level-one-side-by-side)
🔗 [See form control changes in Storybook](https://primer-883531b99b-26139705.drafts.github.io/storybook/?path=/story/components-forms-formcontrol--text-input-playground)
🔗 [See inline link changes in Storybook](https://primer-883531b99b-26139705.drafts.github.io/storybook/?path=/story/components-inlinelink--size-inheritence)

## Supporting resources (related issues, external links, etc):

- [Reference designs in Figma](https://www.figma.com/file/HIEQHWa8Cuw4AZfFisALJV/Contentful-Templates?type=design&node-id=1262-3386&mode=design&t=oDodcfwcQEwU6fJk-4)

## Contributor checklist:

- [ ] All new and existing CI checks pass
- [ ] Tests prove that the feature works and covers both happy and unhappy paths
- [ ] Any drop in coverage, breaking changes or regressions have been documented above
- [ ] New visual snapshots have been generated / updated for any UI changes
- [ ] All developer debugging and non-functional logging has been removed
- [ ] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:

Link colors in dark mode:

<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">

Screenshot 2023-09-25 at 13 10 39

 </td>
<td valign="top">

Screenshot 2023-09-25 at 13 11 15

</td>
</tr>
</table>

Link underline across multiple lines:

<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">

Screenshot 2023-09-26 at 11 44 39

 </td>
<td valign="top">

Screenshot 2023-09-26 at 11 44 53

</td>
</tr>
</table>

New form examples:

https://github.com/primer/brand/assets/13340707/8ad4e1fb-2dde-4b86-9c2c-4895647088a0

### CODE REVIEW

**Comment by natalie-iv** [comment]
@rezrah Could you, please, add link to Storybook?

**Comment by rezrah** [comment]
> @rezrah Could you, please, add link to Storybook?

@natalie-iv Links are active in the description now. The deployment takes a while to complete, so worth checking back if they're not there straight away.

**Review by josepmartins — COMMENTED** [review]
> FormControl labels from 14px to 16px to match labels in Figma

Labels on Figma are actually `14px`, and the input font-size is `16px` (`14px` in React). 
Shouldn't we change the input font-size and not the label? Let me know unless I missed something and we need to make that change in the Figma library.

cc @jesussandreas @natalie-iv 







 
Screenshot 2023-09-26 at 15 46 57

**Comment by natalie-iv** [comment]
@rezrah As agreed in [this thread](https://github.slack.com/archives/C04NS86UW5Q/p1695738259742599) let's keep labels and hints 16px font-size.

**Review by natalie-iv — APPROVED** [review]

**Comment by rezrah** [comment]
Thanks for reviewing this, @natalie-iv 👍 

> @rezrah As agreed in [this thread](https://github.slack.com/archives/C04NS86UW5Q/p1695738259742599) let's keep labels and hints 16px font-size.

Just to clarify, I've rolled back to 14px based on the most recent conversations in Slack. We'll revise all form components together down the line, including applying the 16px bump to labels. Is that okay @natalie-iv?


> 1. One small thing I notices is the wrong border thickness of Verify Button, it should be 1px and it should be without an icon. Could you please check it?

This button would be part of the third party widget we use for security verification. We don't have a way to replicate this properly in our Storybook, so I've intentionally left out of scope. We also don't have that button style in Primer Brand. We'll leave this for eng teams to implement in the final forms.

> 2. "Unsubscribe" word here should be also a link (see example https://github.com/enterprise/contact?scid=&utm_campaign=2023q3-site-ww-PremiumSupport&utm_content=Premium+Support&utm_medium=referral&utm_source=github)

I've added a link 👍, but used a placeholder url to avoid linking to our production unsubscribe page.

> 3. Message field in the form should not be marked with asterisk (*). Also the phone, but this one I'm checking right now.

Fixed, thank you 👍

**Review by josepmartins — APPROVED** [review]

**Pull request merged**
