### PR TITLE
SubNav component

### PR DESCRIPTION
**Pull request by rezrah**
## Summary

Part of https://github.com/github/primer/issues/3087

Adds a new, experimental status `SubNav` component.

🔗 [Preview it here](https://primer-71f25affb6-26139705.drafts.github.io/storybook/?path=/story/components-subnav-features--example-usage)

## What should reviewers focus on?

- Reviewing design parity with its Rails counterpart

## Steps to test:

1. [Documentation](https://primer-71f25affb6-26139705.drafts.github.io/components/SubNav) 
1. [Storybook examples](https://primer-71f25affb6-26139705.drafts.github.io/storybook/?path=/story/components-subnav-features--example-usage)

## Supporting resources (related issues, external links, etc):

- [Prior art / Rails counterpart](https://github.com/features/copilot)

## Contributor checklist:

- [x] All new and existing CI checks pass
- [ ] Tests prove that the feature works and covers both happy and unhappy paths
- [x] Any drop in coverage, breaking changes or regressions have been documented above
- [x] New visual snapshots have been generated / updated for any UI changes
- [x] All developer debugging and non-functional logging has been removed
- [x] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:
Screenshot 2024-03-08 at 11 18 53
Screenshot 2024-03-08 at 11 18 50

### CODE REVIEW

**Review by nsolerieu — APPROVED** [review]
LGTM 🟢

Mobile is especially nice and minimal, well done

**Comment by danielguillan** [comment]
This is looking great! A few things I've noticed:

1. The menu breaks when the viewport width is exactly `1012px`.
2. On smaller screens, the current page name should be included in the dropdown menu and be focusable/clickable. Currently, only the chevron allows access to the menu.
3. There appears to be a focus order problem with the menu. I'm not sure if it's related to the component or specific to the example story.
4. Users should be able to close the menu by pressing the `esc` key. and by clicking outside.
5. I would add an overlay layer similar to the one on the Copilot page.

---

SubNav menu broken at 1012px

_SubNav when the viewport is 1012px wide._

Chevron is

_Only the chevron triggers the menu_


https://github.com/primer/brand/assets/175638/812ded55-3991-47a1-be03-b0829be2ee3f

_Focus order issue_

**Review by auareyou — APPROVED** [review]
My only observation is that blue feels a little off in terms of contrast in dark mode. I'm not sure if it's because it's on an image or what it is. Everything else looks great. 👍

**Comment by danielguillan** [comment]
@rezrah thanks for the updates!

One last thing from me:

> ✔️ fixed. now the text is clickable/tabbable , behaving the same as current Rails version (albeit with correct element ordering)

Currently, the text and chevron are separate focusable elements. I suggest combining them into a single trigger, like in the rails version (althoug the focus ring there doesn't account for the chevron) and similar to the AnchorNav component.

**Comment by rezrah** [comment]
> @rezrah thanks for the updates!
> 
> One last thing from me:
> 
> > ✔️ fixed. now the text is clickable/tabbable , behaving the same as current Rails version (albeit with correct element ordering)
> 
> Currently, the text and chevron are separate focusable elements. I suggest combining them into a single trigger, like in the rails version (althoug the focus ring there doesn't account for the chevron) and similar to the AnchorNav component.

@danielguillan 👍 I've updated how that toggle works now to be behave similarly to AnchorNav. This is now quite different to the Rails version, but I agree it's better for accessibility.


https://github.com/primer/brand/assets/13340707/bdb9e690-2193-4a0e-aa0d-d5509d2a0f1c

**Review by danielguillan — APPROVED** [review]
🙌 This is great!

**Pull request merged**
