### PR TITLE
Correct vertical alignment of FormControl validation icon

### PR DESCRIPTION
**Pull request by joshfarrant**
## Summary

Nudged the icon up 2px

## What should reviewers focus on?

1. Does it look better?

## Supporting resources (related issues, external links, etc):

- https://github.com/primer/brand/issues/650

## Contributor checklist:

- [x] All new and existing CI checks pass
- [x] Tests prove that the feature works and covers both happy and unhappy paths
- [x] Any drop in coverage, breaking changes or regressions have been documented above
- [x] New visual snapshots have been generated / updated for any UI changes
- [x] All developer debugging and non-functional logging has been removed
- [x] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:

> Please try to provide before and after screenshots or videos

<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">

image

 </td>
<td valign="top">

image

</td>
</tr>

<td valign="top">

image

 </td>
<td valign="top">

image

</td>
</tr>
</table>

### CODE REVIEW

**Comment by joshfarrant** [comment]
Thanks @rezrah. I'll modify the alignment on a per-icon basis and nudge the check slightly higher

**Comment by joshfarrant** [comment]
That's updated, good spot @rezrah.

How did you view it with the grid lines out of interest?

**Comment by rezrah** [comment]
Look much better, thanks @joshfarrant.

I think this regression occurred because we don't have dedicated stories for the validation states that are tracked in our VRT suite. If possible, could you please add some stories under FormControl enabling the `validationStatus` props for both success and error states. We'll then be able to see visual diffs in future.

**Comment by joshfarrant** [comment]
Good suggestion, thanks @rezrah 

That's added, although the changes are lost somewhere in the vrt spec files updates.

I'll rebase and get rid of those changes once https://github.com/primer/brand/pull/670 is in

**Review by rezrah — APPROVED** [review]

**Pull request merged**
