### PR TITLE
Add paddings to large river content

### PR DESCRIPTION
**Pull request by danielguillan**
## Summary

Adds padding to `River__content` on larger viewports

## Steps to test:

- [Review River stories](https://primer-4635941e6a-26139705.drafts.github.io/brand/storybook/?path=/story/components-river--default)

## Supporting resources (related issues, external links, etc):

- Solves https://github.com/github/primer/issues/3927

## Contributor checklist:

- [x] All new and existing CI checks pass
- [x] Tests prove that the feature works and covers both happy and unhappy paths
- [x] Any drop in coverage, breaking changes or regressions have been documented above
- [x] New visual snapshots have been generated / updated for any UI changes
- [x] All developer debugging and non-functional logging has been removed
- [x] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:

<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">

screenshot-sDbPNyjo-001128@2x

 </td>
<td valign="top">

screenshot-Lp7PmRD5-001129@2x

</td>
</tr>
</table>

### CODE REVIEW

**Review by nsolerieu — APPROVED** [review]
Yes please!

**Review by simurai — CHANGES_REQUESTED** [review]
Looks like there should be no padding on the left when the text is on the left side, see [Slack](https://github.slack.com/archives/C04E44ZPNEA/p1727318361523699?thread_ts=1727300820.193859&cid=C04E44ZPNEA).

> @nsolerieu I’d line to get this PR updated and keep the wider gap between left and right sides but not the lateral padding

**Comment by simurai** [comment]
I think it would be this:

Text shown on the **right**:

```
|--- visual 600px ---|  gap 48px  |--------------- content 600px ---------------|
                                  | 64px pad. |----- text 472px ----| 64px pad. |
```                                  

Text shown on the **left**:

```
|--------------- content 600px ---------------|  gap 48px  |--- visual 600px ---|
|----------text 472px--------|-- 128px pad. --|
```

**Comment by danielguillan** [comment]
@simurai @nsolerieu the paddings have been updated 👍

**Review by simurai — APPROVED** [review]
Wow.. so many diffs.. but I think it looks correct. 👍

**Pull request merged**
