### PR TITLE
Prevents column width from overflowing the River component

### PR DESCRIPTION
**Pull request by mperrotti**
## Summary

Closes https://github.com/github/primer/issues/2161

## List of notable changes:

Just a simple style update to sizes River grid columns with `fr` units instead of `%`

## What should reviewers focus on?

How cool and easy CSS grid is.

## Steps to test:

Inspect the River component and confirm that neither column overflows the grid parent.

## Supporting resources (related issues, external links, etc):

n/a

## Contributor checklist:

- [ ] All new and existing CI checks pass
- [ ] Tests prove that the feature works and covers both happy and unhappy paths
- [ ] Any drop in coverage, breaking changes or regressions have been documented above
- [ ] New visual snapshots have been generated / updated for any UI changes
- [x] All developer debugging and non-functional logging has been removed
- [x] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:

<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">

Screenshot 2023-05-03 at 2 38 40 PM

 </td>
<td valign="top">

Screenshot 2023-05-03 at 2 39 14 PM

</td>
</tr>
</table>

### CODE REVIEW

**Review by josepmartins — APPROVED** [review]
LGTM! ❇️

**Review by rezrah — APPROVED** [review]
Thanks @mperrotti, fix works great ✨ 

Could you please add a changeset to the PR before merge? We'll also need to update the visual snapshots, which I've done on your PR via a label.

**Comment by mperrotti** [comment]
@rezrah - any idea what this strange CI error is about?
```
Building Remix app in production mode...
⚠️ REMIX FUTURE CHANGE: The `serverModuleFormat` config default option will be changing in v2 from `cjs` to `esm`. You can prepare for this change by explicitly specifying `serverModuleFormat: 'cjs'`. For instructions on making this change see https://remix.run/docs/en/v1.16.0/pages/v2#servermoduleformat
The path "@primer/react-brand/lib/css/main.css?__remix_sideEffect__" is imported in  but "@primer/react-brand/lib/css/main.css?__remix_sideEffect__" was not found in your node_modules. Did you forget to install it?
✘ [ERROR] Could not resolve "./styles/tailwind.css"

    app/root.tsx:5:34:
      5 │ import tailwindStylesheetUrl from './styles/tailwind.css';
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rezrah** [comment]
> @rezrah - any idea what this strange CI error is about?

It's from our integration tests, where we test each PR against a CLI installation of popular UI frameworks - in this instance it's Remix. Remix made a CLI change upstream recently, which we need to fix on our end, so you can ignore this failure for now.

**Pull request merged**
