### PR TITLE
Remove subsections in navigation

### PR DESCRIPTION
**Pull request by josepmartins**
## Summary

Remove component sub-sections in the documentation navigation and list all components under a single `component` section. This aligns the navigation to the interface guidelines IA. 

cc @emilybrick 

## List of notable changes:

- **removed** component sub-sections, and re-order all components under a single `Components` section

## What should reviewers focus on?

- Documentation:

## Contributor checklist:

- [ ] All new and existing CI checks pass
- [ ] Tests prove that the feature works and covers both happy and unhappy paths
- [ ] Any drop in coverage, breaking changes or regressions have been documented above
- [ ] New visual snapshots have been generated / updated for any UI changes
- [ ] All developer debugging and non-functional logging has been removed
- [ ] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:

> Please try to provide before and after screenshots or videos

<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">

Screenshot 2023-06-16 at 08 38 12

 </td>
<td valign="top">

Screenshot 2023-06-16 at 08 37 56

</td>
</tr>
</table>

### CODE REVIEW

**Comment by josepmartins** [comment]
@emilybrick curious to know what we should do with the `Introduction` and the `Primitives` sections. My proposal:

- `Introduction` -> `Guides`
- `Primitives` section and `Colors` page. If we recommend overrides using CSS variables, not sure if this page adds value to the consumer as it is now. I'd say we could safely remove the page for now.

cc @rezrah 

Screenshot 2023-06-16 at 08 39 02

**Comment by emilybrick** [comment]
> Introduction -> Guides
also +1 for this.

Regarding the Primitives section - defer to what you think makes the most sense. 
> If we recommend overrides using CSS variables, not sure if this page adds value to the consumer as it is now
As long as the user is aware of the current recommended method and it's clear in the docs 👆

**Comment by emilybrick** [comment]
> E.g. we've lost the convenience of co-locating groups of related components, like form-specific ones under one section. We now expect users to scan the entire list of components, where they would previously only need to look beneath the item they're already on. Another example is typography. If you need a Heading component, you will likely also need Text, but there's a risk that some users may not know about its counterpart component now.

We considered doing something _like_ this (possibly) in the future for design IA (grouping components)... but not having the type of component as a top-level section, rather a secondary section _within_ components. The new nav list supports more levels of nesting, is it possible to use that? /cc @rezrah

**Comment by josepmartins** [comment]
Hey @rezrah @emilybrick, thanks for your feedback.

I talked to @emilybrick and explored other solutions to group components, using the [NavList sub items https://primer.style/react/NavList#with-sub-items](https://primer.style/react/NavList), but the UI hides the pages gets hidden under each group by default, which is not desired. Here's a quick example.

Screenshot 2023-06-19 at 17 40 56

I'm closing the PR as we also agree that there's no need for both expressions to have identical IA for now. We'll be in touch if there's a future solution to group components by use case that can work for both Product and Brand 👍 .

**Pull request closed without merging**
