### PR TITLE
Add `instagram` to `MinimalFooterSocialLinks`

### PR DESCRIPTION
**Pull request by simurai**
## Summary

This adds `instagram` to the `MinimalFooterSocialLinks`.

## List of notable changes:

- **added** `instagram` to `MinimalFooterSocialLinks` to avoid Type error

## Steps to test:

When adding `instagram` like

```ts
<MinimalFooter socialLinks={['twitter', 'facebook', 'youtube', 'linkedin', 'github', 'tiktok', 'instagram']}>
```

it works, and the icon is rendered, but there is a Type error that doesn't pass [our CI check](https://github.com/github/githubuniverse.com/actions/runs/5923516310/job/16059302179?pr=1797):

```bash
Type error: Type '"instagram"' is not assignable to type '"twitter" | "github" | "linkedin" | "youtube" | "facebook" | "twitch" | "tiktok"'.

  4 | export const Footer = () => {
  5 |   return (
> 6 |     <MinimalFooter socialLinks={['twitter', 'facebook', 'youtube', 'linkedin', 'github', 'tiktok', 'instagram']}>
    |                                                                                                    ^
```

## Supporting resources (related issues, external links, etc):

- This came up in https://github.com/github/githubuniverse.com/pull/1797#issuecomment-1685914785

## Contributor checklist:

- [x] All new and existing CI checks pass
- [ ] ~~Tests prove that the feature works and covers both happy and unhappy paths~~
- [ ] ~~Any drop in coverage, breaking changes or regressions have been documented above~~
- [ ] ~~New visual snapshots have been generated / updated for any UI changes~~
- [x] All developer debugging and non-functional logging has been removed
- [x] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:

> Please try to provide before and after screenshots or videos

N/A

### CODE REVIEW

**Comment by simurai** [comment]
I _think_ the current CI failures are unrelated? 🤔 I'll update `main` at some point and see if they go away.

**Comment by simurai** [comment]
I _think_ the current CI failures are unrelated? 🤔 I'll update `main` at some point and see if they go away.

**Comment by rezrah** [comment]
> I _think_ the current CI failures are unrelated? 🤔 I'll update `main` at some point and see if they go away.

Yeah, these are being fixed here @simurai https://github.com/primer/brand/pull/400

**Review by rezrah — APPROVED** [review]
👍 Thanks for fixing this @simurai ... LGTM :shipit:

**Pull request merged**
