### PR TITLE
Adjust Label and icon colors

### PR DESCRIPTION
**Pull request by josepmartins**
## Summary

Adjust dark mode color shade in icons (used in `Card` and `Pillar`) and `Label` component.

Fixes https://github.com/github/primer/issues/2384

New color combinations where tested against the default background and provides enough contrast even in normal sized texts

Screenshot 2023-08-04 at 15 25 10

## List of notable changes:

- **updated** color shades to have more contrast and saturation.
- **updated** `Card` default and grey dark background in `hasBackground` options. Fixes gray color that blended with the Card background.

## What should reviewers focus on?

Colors in `Labels` and `Icons` are one shade darker

## Steps to test:

- Storybook:

## Supporting resources (related issues, external links, etc):

- https://github.com/github/primer/issues/2384

## Contributor checklist:

- [ ] All new and existing CI checks pass
- [ ] Tests prove that the feature works and covers both happy and unhappy paths
- [ ] Any drop in coverage, breaking changes or regressions have been documented above
- [ ] New visual snapshots have been generated / updated for any UI changes
- [ ] All developer debugging and non-functional logging has been removed
- [ ] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:

> Please try to provide before and after screenshots or videos

<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">

Screenshot 2023-08-04 at 14 48 34

 </td>
<td valign="top">

Screenshot 2023-08-04 at 14 47 45

</td>
</tr>
</table>

### CODE REVIEW

**Review by rezrah — APPROVED** [review]
Nice! 

Do you know if any colors are expected to change (added/removed/updated) as part of site refactor @josepmartins?

**Comment by josepmartins** [comment]
> Nice!
> 
> Do you know if any colors are expected to change (added/removed/updated) as part of site refactor @josepmartins?

Good question. As far as I'm concerned, Universe and Enterprise latest uses the default black/white color, for instance, in `SectionIntro` and `Hero` components. 

Nor urgent: @ajashams do you know if we expect any changes to the Label color options? [We provide one option x color palette + some gradient options too](https://primer.style/brand/storybook/?path=/story/components-label-features--color&globals=colorMode:all). I remember @samoshin comments around getting rid of gradients in Labels some time ago, wondering if that's still the case.

**Comment by ajashams** [comment]
@josepmartins - Agreed, we're likely **not** moving forward with gradients on labels for any refactored work. I believe we're introducing a light and dark version of one Brand Pillar colors to our [/preview template here](https://www.figma.com/file/m4U5DInCRrbXCwOfWJUfQf/Contentful-Templates?type=design&node-id=1%3A103509&mode=design&t=9QiQXQDQfc2pH9qu-1). But these should inherit colors from our existing Primer-Brand palette. LMK if you have any concerns. We are working on defining that this week.

**Comment by josepmartins** [comment]
> @josepmartins - Agreed, we're likely **not** moving forward with gradients on labels for any refactored work. I believe we're introducing a light and dark version of one Brand Pillar colors to our [/preview template here](https://www.figma.com/file/m4U5DInCRrbXCwOfWJUfQf/Contentful-Templates?type=design&node-id=1%3A103509&mode=design&t=9QiQXQDQfc2pH9qu-1). But these should inherit colors from our existing Primer-Brand palette. LMK if you have any concerns. We are working on defining that this week.

Sounds good @ajashams!

**Pull request merged**
