### PR TITLE
Updates typographic weight defaults Heading component + adds <em> support into SectionIntro

### PR DESCRIPTION
**Pull request by rezrah**
> [!Important]  
> PR includes visual and component API breaking changes. 
> Release tag: `next-minor`

🔗 [Read the rendered changeset for full details](https://github.com/primer/brand/blob/rezrah/add-emphasis-support/.changeset/fair-rocks-return.md) (To be shared with partner teams ahead of a potential release)

🔗  [See these changes in Storybook](https://primer-a340064e6f-26139705.drafts.github.io/storybook/?path=/story/components-heading--scale)

--- 

## Summary

Part of https://github.com/github/primer/issues/2495 and https://github.com/github/primer/issues/2504
Required to unblock https://github.com/github/primer/issues/2517

Adds support for emphasized text into SectionIntro and makes sweeping visual alignment changes to all headings. 

This is an interim step towards applying global heading and text updates at the Primitives layer. This should help make diffing those PR's easier, by removing the `weight` changes from the list of expected changes.

As this will be a visual breaking change, this will first be merged into the `next-minor` branch (when available) and shared with partner teams to gauge impact ahead of a GA release.

## List of notable changes:

- **added** `<em>` composability into SectionIntro
- **updated** SectionIntro font size to be closer to expected 40px (site refactor). Previously  64px, now 48px.
- **updated** All headings now use either bold (size 1) or semibold (2-6) by default
- **removes** `size` prop from FAQ.Heading as this was introduced before `size` was available in Heading. 

## What should reviewers focus on?

- Thoughts on breaking changes
- Anything look out of the ordinary in the visual diffs
- Changeset review. Missing any details?

## Steps to test:

1. Use the PR diff view on the visual snapshots to compare before/afters
1. Open and review Storybook
1. Open and review the docs, which should match Storybook

## Contributor checklist:

- [ ] All new and existing CI checks pass
- [ ] Tests prove that the feature works and covers both happy and unhappy paths
- [ ] Any drop in coverage, breaking changes or regressions have been documented above
- [ ] New visual snapshots have been generated / updated for any UI changes
- [ ] All developer debugging and non-functional logging has been removed
- [ ] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

### New emphasis in SectionIntro component using `<em>`

Placeholder heading with the first two lines in darker color to the rest of the heading

### CODE REVIEW

**Review by langermank — APPROVED** [review]
This aligns with the direction we're going for the breaking changes to typography 👍

**Review by danielguillan — APPROVED** [review]

**Comment by rezrah** [comment]
@langermank @danielguillan - thanks for your reviews so far. Just a heads up that I've hoisted all weight changes to the CSS layer to apply against **all** headings now, instead of component-owned headings only. This is in light of recent decisions to defer type scale changes. Let me know if this changes your reviews in any way, or if you have concerns around doing this.

**Review by JoshBowdenConcepts — APPROVED** [review]

**Review by langermank — APPROVED** [review]
This looks good to me!

**Comment by ajashams** [comment]
Please forgive me and disregard if this is not meant to be 1:1 with our Refactored file. But wanted to clarify a few things based on your notable changes. 

## Feedback

> updated SectionIntro font size to be closer to expected 40px (site refactor). Previously 64px, now 48px.

@rezrah our SectionIntro text should be 64px. I don't think this was clear in our documentation because we're using a different naming convention that doesn't quote align with our system. `Displays` are for heroes, and `headings` are for all other headings within <body>. So technically, our H1 (according to our Refactor file) is our SectionIntro. See image below or review the [refactored type scale here](https://www.figma.com/file/wuhr1sqnv2YEaT4F6dUBbl/2023-Refactor?type=design&node-id=3166%3A6668&mode=design&t=sZBin663q9cdz8Kr-1) 👉 

Screenshot 2023-08-08 at 4 55 10 PM

> updated All headings now use either bold (size 1) or semibold (2-6) by default
This should be fine. According to Refactored headlines, only our Displays use bold and all other Headings use semibold. We may want to introduce medium as an option in the future, but none of those styles have been stress tested. [See my video in slack for more context.](https://github.slack.com/archives/C04NS86UW5Q/p1691530942747349)

**Comment by rezrah** [comment]
Closing in favor of #389, which is based on top of this branch and contains more recent updates.

**Pull request closed without merging**
