### PR TITLE
Add interface guidelines for section intro content length

### PR DESCRIPTION
**Pull request by danielguillan**
Adds content length guidance and do's and don'ts for section intro.

[Docs preview](https://primer-72c54b3967-26139705.drafts.github.io/components/SectionIntro)

### CODE REVIEW

**Review by auareyou — APPROVED** [review]
👍

**Review by rezrah — APPROVED** [review]
:shipit:

**Comment by rezrah** [comment]
@danielguillan Minor comment on something unrelated to this change, but in the SectionIntro guidelines is the text in the images, which seem to be incorrectly justified. Maybe a Figma thing as it doesn't happen in React.

Screenshot 2024-02-20 at 09 33 16

Screenshot 2024-02-20 at 09 34 58

**Review by nsolerieu — APPROVED** [review]
🟢 Well worded @danielguillan 

`Don't use section intro for long form content.` is the biggie here.

----

🙋‍♂️

Perhaps we could also add the fact that one should not stretch the width of the component to flex across the full width of the container (like in the screenshot below?)

Screenshot 2024-02-20 at 3 29 45 PM

The line length could (in a future version of the component) be set depending on the type of heading? or left to the designer to flex according the the grid and specific case? Maybe we should discuss this during PB office hours. Not a blocker

**Pull request merged**
