### PR TITLE
Add IDE component

### PR DESCRIPTION
**Pull request by rezrah**
## Summary

Part of https://github.com/github/primer/issues/3023

Adds an IDE component, with support for a code editor and GitHub Copilot chat 

🔗  [Documentation](https://primer-90c06a6533-26139705.drafts.github.io/components/IDE)
🔗  [Storybook](https://primer-90c06a6533-26139705.drafts.github.io/storybook/?path=/story/components-ide--default&globals=colorMode:dark)

## List of notable changes:

- Added an MVP IDE component covering Chat and Editor use-cases
- Added examples in Storybook 

## What should reviewers focus on?

- Review suitability of the component as an MVP
- Review examples for correctness 

## Supporting resources (related issues, external links, etc):

- [Current Rails version ](https://github.com/lab/editor)

## Contributor checklist:

- [ ] All new and existing CI checks pass
- [ ] Tests prove that the feature works and covers both happy and unhappy paths
- [ ] Any drop in coverage, breaking changes or regressions have been documented above
- [ ] New visual snapshots have been generated / updated for any UI changes
- [ ] All developer debugging and non-functional logging has been removed
- [ ] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:

IDE in River example

### CODE REVIEW

**Comment by simmonsjenna** [comment]
@rezrah Waiting on a small bit of feedback from Nicolas regarding the background color of the scrollbar area in Chat on the Glass version — will follow up with my review approval once I get that figured out. 

I also wanted to call out that the two attached blue block links on the Documentation page seem to lead to dead ends for me at the moment (maybe the URLs will work once this is pushed live; just checking):

Screenshot 2024-04-11 at 8 51 01 AM
874-453d-ad23-3263241f7603">

**Comment by simmonsjenna** [comment]
@rezrah I chatted with @nsolerieu, and we were wondering if it would be possible to change the background of the scroll bar area for Chat to transparent since it is creating some odd shapes when it juts up against the window on the right:

**Proposed background example:**
Screenshot 2024-04-11 at 10 44 10 AM

**Current bg:**
Screenshot 2024-04-11 at 9 11 54 AM

Screenshot 2024-04-11 at 9 11 38 AM

**Review by auareyou — APPROVED** [review]
I have one comment about alignment. The replay and the chat input being aligned makes the component  feel off. Replay button isn't part of the story. I'd either take it out of the window and make it float or I'd separate it somehow visually from everything else. Let me know of this makes sense or you'd love more guidance. I'm here. 

Otherwise LGTM! ✨

**Comment by rezrah** [comment]
> I also wanted to call out that the two attached blue block links on the Documentation page seem to lead to dead ends for me at the moment (maybe the URLs will work once this is pushed live; just checking):
> 

👋 @simmonsjenna that's spot on, it's a preview environment limitation as preview urls don't have a base path.. 

To make these external links work, we need to add `/storybook` to the path.

E.g. https://primer-90c06a6533-26139705.drafts.github.io/storybook/?path=/story/components-ide--default

**Comment by rezrah** [comment]
> we were wondering if it would be possible to change the background of the scroll bar area for Chat to transparent

👍 absolutely. that's done in the latest push. might not have deployed by time you see this, so leaving this before/after just in case 👇 


<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">


Screenshot 2024-04-12 at 14 45 23

 </td>
<td valign="top">
Screenshot 2024-04-12 at 14 45 04



</td>
</tr>
</table>

**Comment by rezrah** [comment]
> The replay and the chat input being aligned makes the component feel off. Replay button isn't part of the story.

👋 @auareyou thanks for the review!

Removed replay from the examples 👍 

Screenshot 2024-04-12 at 14 57 13

**Review by simmonsjenna — APPROVED** [review]
Thank you, @rezrah! 👍 from Site Design.

**Pull request merged**
