### PR TITLE
Update Link and InlineLink styles

### PR DESCRIPTION
**Pull request by mperrotti**
## Summary

Updates the `Link` and `InlineLink` components to conform to the designs spec'd in the 2023 refactor.

## List of notable changes:

- Updated link colors
- Updated link focus styles

## What should reviewers focus on?

Does it match what's in Figma

## Steps to test:

Go to the Link and InlineLink stories in Storybook

## Supporting resources (related issues, external links, etc):

- [Figma mocks](https://www.figma.com/file/wuhr1sqnv2YEaT4F6dUBbl/2023-Refactor?type=design&node-id=1216-168429&mode=design&t=xaBKLvq9OtAuEQHH-4)
- [Primer Brand branch with Figma component updates](https://www.figma.com/file/BJ95AjraesmRCWsKA013GS/branch/9CEoNHTrOswgTKMCzD96Nr/Primer-Brand?type=design&node-id=496%3A8525&mode=design&t=86OL9g23DtogMHeA-1)
- https://github.com/github/primer/issues/2497

## Contributor checklist:

- [ ] All new and existing CI checks pass
- [ ] Tests prove that the feature works and covers both happy and unhappy paths
- [ ] Any drop in coverage, breaking changes or regressions have been documented above
- [ ] New visual snapshots have been generated / updated for any UI changes
- [ ] All developer debugging and non-functional logging has been removed
- [ ] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:

> Please try to provide before and after screenshots or videos

<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">

https://github.com/primer/brand/assets/2313998/a6f903c4-721d-4f32-9b02-20c50f40aff7

https://github.com/primer/brand/assets/2313998/c57c47bd-13ae-46e9-81a6-327f43ad5395

 </td>
<td valign="top">

https://github.com/primer/brand/assets/2313998/d10cdfc5-068e-45f5-9dfb-e39d24119131

https://github.com/primer/brand/assets/2313998/2c1d7845-d02a-4d2f-b048-1c025f67338a

</td>
</tr>
</table>

### CODE REVIEW

**Comment by mperrotti** [comment]
I'm a little confused why the visual regression testing didn't identify any changes 🤔

**Review by josepmartins — APPROVED** [review]
LGTM! 👍

**Comment by josepmartins** [comment]
> I'm a little confused why the visual regression testing didn't identify any changes 🤔

Weird 🤔. I added the "Update snapshots" just in case 🤞

**Comment by jesussandreas** [comment]
question, is the glow on focus being added intentionally? 👀

could we add the border-radius also in there?

**Comment by mperrotti** [comment]
Yes, that’s what was in the mocks. I can open a PR to add a border radius
if the other designers are on board with that.

**Pull request merged**
