### PR TITLE
Add statistic component

### PR DESCRIPTION
**Pull request by rezrah**
## Summary

Added a new statistic component.

Part of https://github.com/github/primer/issues/3367

🔗 [Documentation](https://primer-cada47cf1c-26139705.drafts.github.io/components/Statistic)
🔗 [Storybook](https://primer-cada47cf1c-26139705.drafts.github.io/storybook/?path=/story/components-statistic--playground)

## What should reviewers focus on?

- Verifying design specs
- Checking for potential accessibility issues
- Reviewing docs for typo's and clarity

## Steps to test:

1. Refer to Storybook
1. Refer to docs page

## Supporting resources (related issues, external links, etc):

- [API exploration](https://www.figma.com/board/1F0W3JXGwtqKdKbtyIMf9Y/Brand---Statistic-API-exploration?node-id=5001-723&t=Q36OKbLuIVmZrK0U-0)

## Contributor checklist:

- [ ] All new and existing CI checks pass
- [ ] Tests prove that the feature works and covers both happy and unhappy paths
- [ ] Any drop in coverage, breaking changes or regressions have been documented above
- [ ] New visual snapshots have been generated / updated for any UI changes
- [ ] All developer debugging and non-functional logging has been removed
- [ ] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

## Screenshots:

Screenshot 2024-07-01 at 09 14 55
Screenshot 2024-07-01 at 09 14 49

### CODE REVIEW

**Review by simmonsjenna — COMMENTED** [review]
@rezrah It looks like `--condensed-stretch: 90%;` is overriding `--condensed-stretch: 75%;`, and the latter seems to achieve the narrow style @nsolerieu has in Figma.

Also, should they be H3s or something else styled as headings?

Everything else looks good to me!

**Comment by rezrah** [comment]
Thanks @simmonsjenna 

> It looks like --condensed-stretch: 90%; is overriding --condensed-stretch: 75%;, and the latter seems to achieve the narrow style @nsolerieu has in Figma.

The reason for the override is that 75% for hubot-sans is too tight for general text.

E.g. 

Screenshot 2024-07-01 at 16 54 51

I can override the value for Statistic component though, leave that with me.

> Also, should they be H3s or something else styled as headings?

I think it's fine to use headings semantically here, but we'll double check if there are any assistive tech issue's we'll need to keep in mind here.

**Review by nsolerieu — APPROVED** [review]

**Review by simmonsjenna — APPROVED** [review]

**Review by joshfarrant — APPROVED** [review]
Looks great! Spotted the tiniest thing in the changelog, but will be great to 🚢 this!

**Comment by danielguillan** [comment]
> Also, should they be H3s or something else styled as headings?

> I think it's fine to use headings semantically here, but we'll double check if there are any assistive tech issue's we'll need to keep in mind here.

I also think it's fine to use a heading here. The markup output has a potential issue though where the "heading" and description are currently presented as two separate sibling elements (`h3 + span`), which assistive technology might read as separate items. However, statistics should be read as a single sentence (e.g., "$20M+ given back to our maintainers"). To address this, an option would be to output the description as a part of the heading tag, similar to the [eyebrow pattern described in the Primer documentation](https://primer.style/components/heading#handling-subheadings-eyebrows-and-straplines), unless the `figure` tag wrapping these elements solves this problem somehow?

**Comment by rezrah** [comment]
@danielguillan figure _should_ address that by calling out the caption separately to the statistic, but I agree it's probably better for assistive tech to read it aloud as one sentence. I've removed the <figure> and instead appended the description to the heading. No API changes, everything still looks the same too.

**Review by danielguillan — APPROVED** [review]

**Pull request merged**
