### PR TITLE
Bento component (part 2)

### PR DESCRIPTION
**Pull request by rezrah**
## Summary

🔗 [See it in Storybook](https://primer-7d51dedcc4-26139705.drafts.github.io/storybook/?path=/story/components-bento-features--mixed)
🔗 [Read the documentation](https://primer-7d51dedcc4-26139705.drafts.github.io/components/Bento)

- Continuation and follow-up to https://github.com/primer/brand/pull/390
- Part of https://github.com/github/primer/issues/2431 and https://github.com/github/primer/issues/2447

## List of notable changes:

- **updated** component based on previous design and PR feedback
- **added** new stories to storybook

## What should reviewers focus on?

- Providing design review and signoff. 
- Testing the canary release in active projects

## Steps to test:

1. [Review individual stories in Storybook](https://primer-7d51dedcc4-26139705.drafts.github.io/storybook/?path=/story/components-bento-features--mixed)
1. [Read the documentation](https://primer-7d51dedcc4-26139705.drafts.github.io/components/Bento)
1. Try the canary release

## Supporting resources (related issues, external links, etc):

- [Figma specs](https://www.figma.com/file/BJ95AjraesmRCWsKA013GS/Primer-Brand?type=design&node-id=9686-1011&mode=design&t=teWEIoBV4O0BHR92-4)

## Contributor checklist:

- [ ] All new and existing CI checks pass
- [ ] Tests prove that the feature works and covers both happy and unhappy paths
- [ ] Any drop in coverage, breaking changes or regressions have been documented above
- [ ] New visual snapshots have been generated / updated for any UI changes
- [ ] All developer debugging and non-functional logging has been removed
- [ ] Related issues have been referenced in the PR description

## Reviewer checklist:

- [ ] Check that pull request and proposed changes adhere to our [contribution guidelines](../../CONTRIBUTING.md) and [code of conduct](../../CODE_OF_CONDUCT.md)
- [ ] Check that tests prove the feature works and covers both happy and unhappy paths
- [ ] Check that there aren't other open Pull Requests for the same update/change

### CODE REVIEW

**Comment by ajashams** [comment]
# Site Review
I'm making up names of these "boxes" based on content or where they are in the module. Apologies if my naming is slightly off from what you all have been calling them.

### General observations:
- Heading weights are rendering a bit heavier in the browser, and letter-spacing appears a bit more tight. 

## Desktop 
### Mixed
- [ ] `Stat box:` Stat number is currently set at Display 96px when it should be 112px. 
- [ ] `Stat box:` Spacing between the stat number and sub-copy appears wide. Should be 36px
- [ ] The `customer story box` appears to be using our Heading-3 style _**or**_ a heavier weight. Can we check to make sure it's using our refactored Heading-4 styles (the same as the other smaller ones)? It appears that way in the code, but something feels off. Mixed 3's `customer story box` appears accurate.

### Mixed 2
- [ ] `Top, full column box`: Can we introduce a rule to this Heading, whereby we prevent `widows` and `orphans` from happening? Or does this need to be hardcoded?
- [ ] Top, full column box`: Image is getting cut and isn't rounded
- [ ] `Icon box:` 72px padding between icon and text 

### Mixed 3
- [ ] `Top, river box`: Image should take up half the box width and span 6 columns. 

---

## Mobile
### Mixed 
- [ ] Follow 24px right- and left-padding on text
- [ ] Stat box: Stat size should drop to 80px (check spacing between text and icon)
- [ ] Links should default to `Medium` size
- [ ] Introduce minimum height for all boxes that are image only (445px height)
- [ ] Customer story box: Stacking order should be text first, then image

**Comment by ajashams** [comment]
I think i accidentally found the keyboard shortcut for close PR 😅 . Apologies for that!

**Review by ajashams — CHANGES_REQUESTED** [review]
# 🏁 Context for QA
- I'm making up names of these "boxes" based on content or where they are in the module. Apologies if my naming is slightly off from what you all have been calling them.
- Heading weights are rendering a bit heavier in the browser, and letter-spacing appears a bit more tight. I called out a few of them, but wondering if we could triple-check those are accurate 🙏 
- Tablet and Mobile are still a bit off across all the sets. You can find the [mobile figma comps](https://www.figma.com/file/Suh8BfFWPLnsg1GQN9yAF7?node-id=2284:72440&mode=design#554000645) I've been using for QA here

# ➡️ Mixed
### Desktop 
- [x] `Stat box:` Stat number is currently set at Display 96px when it should be 112px. 
- [x] `Stat box:` Spacing between the stat number and sub-copy appears wide. Should be 36px
- [x] The `customer story box` appears to be using our Heading-3 style _**or**_ a heavier weight. Can we check to make sure it's using our refactored Heading-4 styles (the same as the other smaller ones)? It appears that way in the code, but something feels off. Mixed 3's `customer story box` appears accurate.

### Mobile   
- [x] `Stat box:` Stat size should drop to 80px (check spacing between text and icon)
- [ ] `Links` should default to `Medium` size. Currently wrapping to two lines with floating chevrons.
- [ ] `Video box:` Introduce minimum height at 445px 
- [ ] `Customer story box: `Stacking order should be text first, then image (across all of them)


#  ➡️ Mixed 2
### Desktop   
- [ ] `Top, full column box`: Can we introduce a rule to this Heading, whereby we prevent `widows` and `orphans` from happening? Or does this need to be hardcoded?
- [ ] Top, full column box`: Image is getting cut and isn't rounded
- [ ] `Icon box:` 72px padding between icon and text 

### Mobile 
- [ ] `Top, full column box`: Follow 24px right- and left-padding on text. Currently feels squeezed in box with lots of wrapping. 
- [ ] Increase image height in box container (Brand Engineering)

#  ➡️ Mixed 3 
### Desktop  
- [ ] `Top, river box`: Image should take up half the box width and span 6 columns. 

### Mobile   
- [ ] All boxes: Follow 24px right- and left-padding on text. Currently feels squeezed in box with lots of wrapping. 
- [ ] `Top river box`: Background image doesn't appear to fill the top-left corner
- [ ] `Top river box`: Spacing between text and image should be 
- [ ] `Stat box:` Stat size appears to be different than `Mixed` and `Mixed 2` sets
---

**Review by josepmartins — APPROVED** [review]
LGTM!

Just a minor comments around the examples:

Some comments:

In mixed 2 examples, the first item has a min-height that affects the gap spacing, ideally we should use the gap-row values so every item height is consistent across the bento. 

<table>
<tr>
<th>Using height</th> <th> Without height </th>
</tr>
<tr>
<td valign="top">

Screenshot 2023-09-14 at 08 54 06

 </td>
<td valign="top">

Screenshot 2023-09-14 at 08 56 26

</td>
</tr>
</table>

In mixed 3 examples, a couple of items spans full width in tablet size, leaving too much white space. Proposal: keep them in the same row and then use full width in mobile, similar to the first two items in the Mixed 1 example 

<table>
<tr>
<th>Tablet Mixed 3 </th> <th> Tablet mixed 1 </th>
</tr>
<tr>
<td valign="top">

Screenshot 2023-09-14 at 09 02 05

 </td>
<td valign="top">

Screenshot 2023-09-14 at 09 03 30

</td>
</tr>
</table>

**Comment by rezrah** [comment]
Thanks @josepmartins, I've updated the examples with your recommendations. 

<table>
<tr>
<td>

Screenshot 2023-09-14 at 09 16 48


</td>
<td>

Screenshot 2023-09-14 at 09 19 09


</td>
</tr>
</table>

On the row gap point, I think we may see some challenges on limiting height in-between various span sizes. E.g. the distance between 6 and 7 values is ~100px. Do you happen to know of a workaround?

@ajashams - Primer Design have completed the design review ✅. Are you able to give this another pass please? (It hasn't changed much since we spoke yesterday, and your feedback has mostly been resolved).

**Comment by josepmartins** [comment]
> On the row gap point, I think we may see some challenges on limiting height in-between various span sizes. E.g. the distance between 6 and 7 values is ~100px. Do you happen to know of a workaround?

One workaround would be to decrease the Bento row height which now uses `--base-size-80` to something more granular (lets say 48px?). Using that value the first bento item can use `auto/span 9` which translates to a total 688px height.

This would require adjusting the rest of bento items in the examples though 😓 

Screenshot 2023-09-14 at 10 51 50

**Comment by ajashams** [comment]
## Tablet Feedback

- [ ] Some weird alignment happening on that stat bento (img 1)
- [ ] For the two side-by-side bentos in desktop (img 2), we are stacking them in Tablet (img 3). Can we keep those side-by-side or does it feel crammed?

| Stat bento | Side-by-side Desktop | Stacked Tablet |
| --- | --- | --- |
| Screenshot 2023-09-14 at 9 58 20 AM | Screenshot 2023-09-14 at 10 05 07 AM | Screenshot 2023-09-14 at 9 59 08 AM

**Review by ajashams — APPROVED** [review]
@rezrah and I adjusted the padding in Tablet and Site is feeling good about where this is going! 👍

**Pull request merged**
